import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth, signOut } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between border-b border-zinc-200 px-6 py-3 text-sm dark:border-zinc-800">
          <a href="/" className="font-medium text-black dark:text-zinc-50">
            内容一键多平台改写
          </a>
          <nav className="flex items-center gap-4">
            <a href="/pricing" className="text-zinc-600 hover:underline dark:text-zinc-400">
              购买套餐
            </a>
            {session?.user ? (
              <>
                <span className="text-zinc-600 dark:text-zinc-400">{session.user.email}</span>
                <form
                  action={async () => {
                    "use server";
                    await signOut({ redirectTo: "/" });
                  }}
                >
                  <button type="submit" className="text-zinc-600 underline dark:text-zinc-400">
                    退出
                  </button>
                </form>
              </>
            ) : (
              <a href="/login" className="text-black underline dark:text-zinc-50">
                登录
              </a>
            )}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
